### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by gustf** [addaleax/node-levenshtein-sse#1]
Would be nice with some benchmarks comparing different implementations to see how much faster this is to other solutions.

**Comment by addaleax** [comment]
Agreed. I can tell you a few things in advance, though:
- If all you are going to pass to this library are small strings, you likely won’t have much of an advantage by using native code (and especially hardware optimizations, which _require_ at least 16 array/string/… entries).
- This means that the existing benchmarks from other modules are useless. It would probably be nice to have some kind of graph as the output, relating string length to ops/sec.
- Adding `fn(fs.readFileSync('bench.js', 'utf-8'), fs.readFileSync('index.js', 'utf-8'));` to the [`bench.js`](https://github.com/sindresorhus/leven/blob/master/bench.js) from the `leven` module shows a 7× performance gain with levenshtein-sse, as compared to any of the other modules listed there.

**Comment by gustf** [comment]
I agree, benchmarks/output would be best with the lengths, as it reflects the size of the "matrix".

7x performance is pretty imressive! Good work I must say! :+1:

**Comment by addaleax** [comment]
Added a bit of benchmarking – I guess we’ll see how well this captures the performance here.

**Comment by addaleax** [comment]
I don't think I'll actually get around to doing this :D
